import asyncio
import httpx
import json

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "llama3.2"

# A basic pairwise comparison prompt
PROMPT_TEMPLATE = """You are an impartial judge. Evaluate which answer is better.

Question: {question}

Answer A: {answer_a}
Answer B: {answer_b}

Output ONLY valid JSON matching: {{"winner": "A" or "B" or "Tie", "reasoning": "..."}}
"""

async def run_judge(question: str, ans_a: str, ans_b: str, order: str) -> dict:
    prompt = PROMPT_TEMPLATE.format(question=question, answer_a=ans_a, answer_b=ans_b)
    
    async with httpx.AsyncClient(timeout=120.0) as client:
        res = await client.post(OLLAMA_URL, json={
            "model": MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.0}
        })
        
        raw_response = res.json().get("response", "")
        # Fallback parser logic
        start = raw_response.find("{")
        end = raw_response.rfind("}")
        if start != -1 and end != -1:
            return json.loads(raw_response[start:end+1])
        return {"winner": "Error", "reasoning": "Parse Failed"}

async def main():
    question = "What is LanceDB?"
    # Answer 1 is slightly worse, Answer 2 is slightly better
    ans_1 = "LanceDB is a database."
    ans_2 = "LanceDB is an open-source vector database designed for AI and RAG applications."

    print("==================================================")
    print("🔎 EXECUTING POSITION BIAS PROBE (A/B SWAP TEST)")
    print("==================================================\n")
    print(f"QUESTION: {question}\n")

    # Order 1: Ans_1 is A, Ans_2 is B
    print("--------------------------------------------------")
    print("[RUN 1: ORIGINAL ORDER]")
    print(f"-> Answer A (Short - generated by Qwen 1.5b):    '{ans_1}'")
    print(f"-> Answer B (Detailed - generated by Llama 3.2): '{ans_2}'")
    print("--------------------------------------------------")
    res1 = await run_judge(question, ans_1, ans_2, "Order 1")
    print(f"VERDICT: Winner is {res1['winner']} (Judged by Llama 3.2)")
    print(f"REASONING: {res1['reasoning']}\n\n")

    # Order 2: Swap them! Ans_2 is A, Ans_1 is B
    print("--------------------------------------------------")
    print("[RUN 2: SWAPPED ORDER]")
    print(f"-> Answer A (Detailed - generated by Llama 3.2): '{ans_2}'")
    print(f"-> Answer B (Short - generated by Qwen 1.5b):    '{ans_1}'")
    print("--------------------------------------------------")
    res2 = await run_judge(question, ans_2, ans_1, "Order 2")
    print(f"VERDICT: Winner is {res2['winner']} (Judged by Llama 3.2)")
    print(f"REASONING: {res2['reasoning']}\n\n")

    print("==================================================")
    print("📊 BIAS ANALYSIS RESULT")
    print("==================================================")
    # Analyze Flip Rate
    if res1["winner"] == "A" and res2["winner"] == "A":
        print("🚨 POSITION BIAS DETECTED: The model blindly voted for Answer A regardless of quality.")
        print("Flip Rate: 100%")
    elif res1["winner"] == "B" and res2["winner"] == "A":
        print("✅ NO BIAS DETECTED: The model correctly identified the 'Detailed' answer both times.")
        print("Flip Rate: 0%")
    else:
        print("⚠️ INCONCLUSIVE: Result was inconsistent or tied.")
    print("==================================================")

if __name__ == "__main__":
    asyncio.run(main())
